#!/bin/bash
dir="$1"
target="$dir/skybox.jpg"
if [ -e $target ]; then
	rm $target
fi

montage  "white.jpg" "$dir/top.jpg" "white.jpg" "white.jpg" \
	"$dir/left.jpg" "$dir/front.jpg" "$dir/right.jpg" "$dir/back.jpg" \
	"white.jpg" "$dir/bot.jpg" "white.jpg" "white.jpg" \
	-tile 4x3 -geometry +0+0 "$target"
